### ISSUE TITLE
log ip address of client 

### ISSUE THREAD

**Issue by snimavat** [indexzero/http-server#328] opened 2016-11-18 13:09 UTC
is there a way to log the ip address of the client ?

**Comment by derhuerst** [comment] 2016-11-18 18:05
afaik there's not way.

**Comment by snimavat** [comment] 2016-11-19 04:44
@derhuerst can we have this please

**Comment by derhuerst** [comment] 2016-11-19 11:32
@snimavat The maintainers of this module are pretty busy, telling by the number of open issues & PRs. Let's wait for them to give an opinion on wether they want this functionality or not.

If you wanted to do this by yourself, you could implement your own `options.logFn`.

**Comment by thornjad** [comment] 2019-02-05 22:58
Duplicate of #184

**Closed by thornjad** 2019-02-05 22:58 UTC
Labels: duplicate
