### ISSUE TITLE
http-server repeatedly show GET /sockjs-node/info? error

### ISSUE THREAD

**Issue by ghost** [indexzero/http-server#283] opened 2016-06-01 08:28 UTC
I installed http-server globally ,but when I run it in my project ,it shows error repeatedly. The error shows below:

```
[Wed Jun 01 2016 16:11:42 GMT+0800 (中国标准时间)] "GET /sockjs-node/info?t=1464
768702939" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/50.0.2661.102 Safari/537.36"
[Wed Jun 01 2016 16:11:42 GMT+0800 (中国标准时间)] "GET /sockjs-node/info?t=1464
768702939" Error (404): "Not found"
[Wed Jun 01 2016 16:11:48 GMT+0800 (中国标准时间)] "GET /sockjs-node/info?t=1464
768708939" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/50.0.2661.102 Safari/537.36"
[Wed Jun 01 2016 16:11:48 GMT+0800 (中国标准时间)] "GET /sockjs-node/info?t=1464
768708939" Error (404): "Not found"
[Wed Jun 01 2016 16:11:54 GMT+0800 (中国标准时间)] "GET /sockjs-node/info?t=1464
768714939" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/50.0.2661.102 Safari/537.36"
[Wed Jun 01 2016 16:11:54 GMT+0800 (中国标准时间)] "GET /sockjs-node/info?t=1464
768714939" Error (404): "Not found"
```

I uninstall http-server and reinstall it again ,but still can't work,then ,I uninstall Chrome and reinstall it again ,still don't work.But I'm pretty sure that the project I run in http-server can be accessed .Anybody has any clue?

**Comment by derhuerst** [comment] 2016-06-01 11:00
Is there a file `./sockjs-node/info` in the directory you ran `http-server` in?

You can optionally pass a "target" directory to serve. Have you tried that with an absolute path? Like `http-server /path/to/my/directory`.

**Comment by thornjad** [comment] 2019-02-05 22:59
Closing since I can't reproduce and the original poster deleted their account.

**Closed by thornjad** 2019-02-05 22:59 UTC
