### ISSUE TITLE
Crash when sending big file (43GB)

### ISSUE THREAD

**Issue by botanegg** [indexzero/http-server#84] opened 2014-08-13 14:54 UTC
Is this the norm?

"GET /ph.tar"

![- 13 08 2014 - 22 39 35](https://cloud.githubusercontent.com/assets/752322/3907152/26ac73a8-22f9-11e4-84b3-6ee5f8634cfb.png)
![- 13 08 2014 - 22 42 25](https://cloud.githubusercontent.com/assets/752322/3907151/26a9c432-22f9-11e4-9e6d-2e84858ea945.png)

Transmission file size 43GB :laughing:

**Comment by freerunnering** [comment] 2015-01-23 04:00
Tried to stream a video (1.04GB) on my local network and it used a constant 30% CPU until I killed it, didn't notice the memory usage.

**Comment by indexzero** [comment] 2015-03-19 11:12
Going to close this as a duplicate of #138.

**Closed by indexzero** 2015-03-19 11:12 UTC
