### ISSUE TITLE
Splat route

### ISSUE THREAD

**Issue by captDaylight** [indexzero/http-server#170] opened 2015-08-05 22:09 UTC
While developing my web app, it's handy to have the server to serve up the site regardless of the route. All my routing is being handled on the front end.

**Comment by jantimon** [comment] 2015-08-13 08:29
Same as #148 and #80

**Comment by indexzero** [comment] 2015-09-22 01:13
Thanks @jantimon. Duplicate of #80.

**Closed by indexzero** 2015-09-22 01:13 UTC
