### ISSUE TITLE
Is there any way to log the IP address of the client?

### ISSUE THREAD

**Issue by trd** [indexzero/http-server#375] opened 2017-06-13 08:51 UTC
It is a very good and useful development server. I'm using it for everything, but sometimes, while debugging, I need to see the IP address in its console logs. 
Does this sound useful for somebody else?
Thank you.

**Comment by Polyergic** [comment] 2017-08-18 15:29
Duplicate of #184, pull request submitted in #187

**Closed** 2019-02-03 21:15 UTC
Labels: duplicate
