### ISSUE TITLE
Can't start it from node 5.0.0 - Can't find module `colors`

### ISSUE THREAD

**Issue by gepser** [indexzero/http-server#209] opened 2015-11-10 04:19 UTC
This is simple, when I try to run the command `http-server` from `node 5.0.0` I get this error:

```
~  http-server
module.js:339
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/bin/http-server:5:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
```

But, if I run the same command with `node 4.2.2` everything works just fine.

I am using `nvm` to switch between node versions.

**Comment by yanyu0517** [comment] 2015-11-11 03:42
I have the same problem

**Comment by indexzero** [comment] 2015-11-11 03:52
PR welcome. Not sure when I'll have the time to dig into this.

**Comment by nankathi** [comment] 2016-06-21 22:31
i have the same problem :(

**Comment by derhuerst** [comment] 2016-06-21 22:47
It seems like [the Travis builds run neither on Node 5 nor on Node 6](https://travis-ci.org/indexzero/http-server/builds/110313732). That would be a first step towards proper support, right?

**Comment by thornjad** [comment] 2018-10-28 03:34
I am not able to reproduce this, `http-server` runs for me on both node 5.0.0 and 5.12.0

**Comment by thornjad** [comment] 2019-04-15 16:32
Closing since Node 5.x.x is no longer maintained.

**Closed by thornjad** 2019-04-15 16:32 UTC
