### ISSUE TITLE
*Bug*: 127.0.0.1 sent an invalid response.

### ISSUE THREAD

**Issue by fnick851** [indexzero/http-server#530] opened 2019-05-20 21:07 UTC
*bug*

http-server at a directory root. The directory has a folder and several HTML files.

**What did you expect to happen?**
Should serve the directory (list of file) at:
  http://10.101.102.147:8080
  http://192.168.1.217:8080
  http://127.0.0.1:8080

**What actually happened? Please include the actual error trace and / or stack trace if applicable.**

From Chrome: 
This page isn’t working 
127.0.0.1 sent an invalid response.
ERR_INVALID_REDIRECT

Not sure why. Tried to change port number still the same.
Terminal log shows the request was made: 
Starting up http-server, serving ./
Available on:
  http://10.101.102.147:8080
  http://192.168.1.217:8080
  http://127.0.0.1:8080
Hit CTRL-C to stop the server
[2019-05-20T21:01:43.713Z] "GET /" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
(node:13064) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[2019-05-20T21:01:44.992Z] "GET /" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
[2019-05-20T21:01:46.005Z] "GET /" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
[2019-05-20T21:01:47.277Z] "GET /" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
[2019-05-20T21:01:48.748Z] "GET /" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"

But Chrome refuses to list the directory.

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **http-server version:** 0.11.1
- **Platform:** Windows 7 Enterprise / Google Chrome

**Other information (related issues, suggestions for a fix, etc):**

**Comment by jamesanewman** [comment] 2019-05-21 09:24
I had a similar issue, I believe this is the same problem as found here:

https://github.com/indexzero/http-server/issues/525

The is not a full resolution yet but this page has a number of workarounds that you can try.  BTW I had the same problem on Edge and Firefox.

**Comment by thornjad** [comment] 2019-05-21 18:11
Duplicate of #525

**Closed by thornjad** 2019-05-21 18:11 UTC
