### ISSUE TITLE
Server process keeps running in background after stopping server (Windows 10, Node 6.95)

### ISSUE THREAD

**Issue by pablobarria** [indexzero/http-server#346] opened 2017-02-23 19:55 UTC
Greetings,

I'm using Node 6.9.5 on Windows 10. I've been using http-server (installed globally) to test out Webpack generated builds. However, It often happens that after quitting the server with Ctrl+C, it will continue to run (shows up on the task manager, and I can still visit the localhost address).  I'm launching http-server from Powershell.

Strangely enough, it will allow me to run the webpack-dev-server on the same port, but then it will serve the static build instead (or whatever I was serving with the lingering http-server process).

The problem is actually very easy to fix (just kill the processes) once you know is there, but it was very confusing at first. I mention Webpack because it was relevant to my use case and how I came across the issue, but I don't think the problem has anything to do with it.

Thanks.

**Comment by BobbyMcWho** [comment] 2017-03-13 13:27
This same issue is plaguing me currently. @pablobarria what process is the exact one I need to kill?

**Comment by pablobarria** [comment] 2017-03-13 14:13
I basically kill everything that's labeled nodejs. Since I don't really run background node processes other than development servers for testing purposes, I can afford this approach.

Also, I've noticed that the webpack-dev-server also seems to linger after being killed, so maybe this is a larger Node or Node on Windows issue. The difference being that the webpack-dev-server keeps updating everytime I reboot it, unlike the http-server that once ran remains serving the same files until killed.

Hope this helps.

**Comment by BigBlueHat** [comment] 2017-06-21 15:04
So. I'm running the same stack, but using bash (via mingw) rather than PowerShell. I just tested this in PowerShell, and it closes the process correctly.

If `webpack-dev-server` is also hanging around, this is likely not an issue with `http-server` itself, but with Node's process management (perhaps in that version of Node). I'm using Node 7.10.0, atm which doesn't seem to suffer from this issue.

@pablobarria `http-server` has a default cache time of 3600 seconds (so, 60 minutes). If you want it to be shorter, pass `-c 1` for one second caches or even `-c -1` to avoid the caching altogether. That should fix the confusion about `http-server` returning older files.

It's also possible that the cache default is causing the browser to not actually re-request the file. The browser is likely just returning things from cache and not checking the server--as designed. So, running `http-server` with the defaults, requesting a few things, then killing the server would mean you could still get those same things for another 50+ minutes. 😃 Handy. 😄

**Comment by pablobarria** [comment] 2017-06-21 15:24
As I said, this is something I learned to Ctrl+Alt+DeLiveWith. I'm not closing the issue because I guess it is useful for the project to be aware of this, but it is probably a larger Node+Windows issue.

**Comment by BigBlueHat** [comment] 2017-06-22 19:23
Since this is not an `http-server` issue (afaict), I'm going to go ahead and close it--so I can find the needles in haystacks. 😃 It'll still be on the githubz if others have this issue.

Feel free to reopen this issue if you find more data about what might be causing this with `http-server` specifically. Thanks!

**Closed by BigBlueHat** 2017-06-22 19:23 UTC
