### ISSUE TITLE
--proxy does not work correctly

### ISSUE THREAD

**Issue by astoilkov** [indexzero/http-server#148] opened 2015-04-07 11:50 UTC
Maybe I am missing something. I want to proxy to the root index.html file when the specified URL is invalid. I am using:
```
http-server -a localhost -p 8000 -c-1 -o -P http://localhost:8000/index.html
```

However, this causes some kind of infinite recursion and does not work. Note that the --P options works for external sites.

**Comment by igorprado** [comment] 2015-04-09 17:35
+1

I'm trying the exactly same thing here.

**Comment by jantimon** [comment] 2015-04-15 20:00
Well this cannot work because the the path is ignored - the above config will just proxy to http://localhost:8000/

So it will redirect `localhost:8000/invalid.html` to `localhost:8000/invalid.html`.

**Comment by pcvandamcb** [comment] 2015-07-14 10:48
If you want to work with history pushstate, you need all paths to be directed to the application root. How can you accomplish this with http-server? Besides abusing the proxy setting, I can't figure out any other way.

**Comment by jantimon** [comment] 2015-07-14 11:22
the proxy wont help you - afaik right now there is no way but abusing the 404 page.

**Comment by indexzero** [comment] 2015-09-22 01:14
Thanks @jantimon. Duplicate of #80.

**Closed by indexzero** 2015-09-22 01:14 UTC
