### ISSUE TITLE
Support http-server -p 0

### ISSUE THREAD

**Issue by ahmetb** [indexzero/http-server#386] opened 2017-07-24 03:39 UTC
On all major OSes Linux, Mac and Windows, if a process binds to port 0, the system randomly assigns a port number above 1024 that is not being used. For example:

```
$ python -m SimpleHTTPServer 0
Serving HTTP on 0.0.0.0 port 62601 ...
```

However http-server currently does not support this, and uses the default port number:

```
$ http-server -p 0
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8080
  http://10.234.242.146:8080
Hit CTRL-C to stop the server
```

**Comment by BigBlueHat** [comment] 2017-08-03 19:00
Likely this would be a good shorthand (or alternative specification) for the `--find-port` param: #363 

If you'd like to continue/finish that work, I'd be most appreciative!

**Comment by ahmetb** [comment] 2017-08-03 19:19
@BigBlueHat I'm not very good at node.js at all, I'm just a user of this software. I prefer to defer this to someone who can do it better.

**Comment by harttle** [comment] 2017-08-04 02:38
http-server currently using [portfinder](https://www.npmjs.com/package/portfinder) to find a free port, which starts at a basePort default to 8080. A random port above 1024 is not feasible currently.

As mentioned by @derhuerst in #332, it will be a regression to use a random port rather than to fallback to next available. 

While in my opinion, you don't need a perfect random port but only one available. Is it acceptable to make `-p 0` an alias to `-p 8080 --find-port`?

**Comment by BigBlueHat** [comment] 2017-08-04 14:50
@harttle the `-p 0` === `-p 8080 --find-port` seems sensible and consistent with how SimpleHTTPServer handles that `0` value.

#363 has some code for this already.

As long as whatever we do still allows for the specification of an *exact* desired port (with a sensible error thrown if it conflicts) and adds the ability to find a random available port (via `--find-port`) than, I think we're good to go.

@harttle any interest in completing the #363 code? 😃

**Comment by harttle** [comment] 2017-08-04 16:58
#364 has already implemented this.😃 With `(!port || findPort)`, `-p 0` equals `-p <Truthy> --find-port`.

**Comment by ahmetb** [comment] 2017-08-04 18:02
@harttle I'm missing the point of --find-port. `-p 0` should just make --find-port obsolete as OS guarantees to assign a port number that is unused.

**Comment by BigBlueHat** [comment] 2017-08-04 19:54
@ahmetb the other use case is finding a port when the one you specified isn't available: `-p 8080 --find-port`.

However, I imagine that sort of scenario to be less common. If I've specified a port, I *need* the system to throw an error and not run as my client(s) expect a specific port and would (in that scenario) have no way of knowing what the new one was--without something reading the console...

So. The options, I suppose are:
1. `-p 0`
2. `--find-port` (with no `-p`)--identical meaning as 1 above
3. `-p 1234 --find-port`

Given that 1 and 2 are identical in purpose/use. Do we need the feature that 3 provides?

**Comment by ahmetb** [comment] 2017-08-04 21:01
I've never seen a server application that works like "try this port but if it fails, listen on a randomly assigned port" mostly because I believe it's not a real use case. In most cases, the deployment orchestrator can pick a random port for the application and pass that to the application using `-p 0` or a `PORT` environment variable or by re-binding the port in case of containers (Docker etc).

So I am thinking `-p 8080 --find-port` is not a real-world requirement, but I might be wrong.

**Comment by harttle** [comment] 2017-08-04 23:50
I happen to have this need to bind 8000+ ports. In my work place, ports under 8000 are blocked thus I need to bind a random port above 8000. So `portfinder` implements exactly what I need:

Specify a basePort, and fallback to next if unavailable.

**Comment by BigBlueHat** [comment] 2017-08-11 15:50
@harttle good use case. Thanks!

Currently, if you don't define a port, other executions of `http-server` will increment the default (i.e. 8080, 8081, etc.).

However, if you select a port (9000, say), then doing that a second time, throws the `EADDRINUSE 0.0.0.0:9000` error.

Adding `--find-port` to the mix would allows for handling @harttle by setting a new `basePort` value and letting `portfinder` do the incrementing it does not via the default:
https://github.com/indexzero/http-server/pull/364/files

The `-p 0` option seems to amount to the default behavior of not defining a `-p` at all (i.e. `http-server .`)--given that it will find the next available port after the default of `8080`. So. I'm not sure that `-p 0` is adding any value. @ahmetb thoughts on that?

**Comment by ahmetb** [comment] 2017-08-11 19:35
@BigBlueHat I don't have strong opinions. I haven't heard of a practical use of fallback ports ever at all, that's it. I'm okay anyway, just wanted to suggest that `-p 0` is the UNIX/Windows convention of finding a random port using the OS.

**Comment by BigBlueHat** [comment] 2017-08-11 19:54
@ahmetb gotcha. @harttle's use case seems to be legit. 😃 

@ahmetb fwiw, `portfinder` does have a `getPorts()` feature that could be used to handle the `-p 0` case:
https://github.com/indexzero/node-portfinder/blob/master/lib/portfinder.js#L192-L220

It wouldn't be "random" so much as "next available" (starting from the default). But then...that's right back to the default anyhow. 😕 So. Not sure we'll be doing `-p 0` unless someone finds a real need for an actually *random* port (which could also be doable, but it'd be lots of available port checking + random selection from that list...).

Anyhow. I'm going to close this one and move the focus back to #364.

Thanks for all the input, folks!

**Closed by BigBlueHat** 2017-08-11 19:54 UTC

**Comment by thornjad** [comment] 2021-07-12 20:28
This functionality is actually already supported, now documented in 84758e03827eae14d2dc3754d6d1ea88ff3d8241
