### ISSUE TITLE
Can not  visit localhost:8080, but localhost:8080/index.html is fine

### ISSUE THREAD

**Issue by chaishi** [indexzero/http-server#540] opened 2019-06-10 08:57 UTC
**Do you want to request a *feature* or report a *bug*?**
It's  a  **Question**

**If the issue is a bug report, please provide the steps to reproduce it. Please include the actual command causing the issue if applicable.**

Follow  is the content,
 -  dist
     - index.html

Run  this  command,
```
http-server dist
```

**What did you expect to happen?**
I  hope I  can visit localhost:8082,  but  the  browser shows something  wrong
![image](https://user-images.githubusercontent.com/11605702/59184297-6cecd780-8ba0-11e9-8bc0-1b3c314fdead.png)

If  I visit localhost:8082/index.html, it's  fine.
![image](https://user-images.githubusercontent.com/11605702/59184436-b3423680-8ba0-11e9-8205-5576fa2d600c.png)

And I don't  know why... 

**What actually happened? Please include the actual error trace and / or stack trace if applicable.**

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **http-server version:**  ^0.11.1
- **Platform:** windows

**Other information (related issues, suggestions for a fix, etc):**

**Comment by the-simian** [comment] 2019-06-10 19:26
I am also currently experiencing this on `v 0.11.1`

![image](https://user-images.githubusercontent.com/954596/59220934-ba127e80-8b8b-11e9-959e-82b47f78fba7.png)

this is in Chrome

**Comment by the-simian** [comment] 2019-06-10 19:27
Hey, heads up this is a duplicate of #525  actually.

**Comment by h1ve2** [comment] 2019-06-11 07:04
+1

**Comment by h1ve2** [comment] 2019-06-11 07:04
This problem does not occur in previous versions

**Comment by thornjad** [comment] 2019-06-11 15:54
Duplicate of #525

**Closed by thornjad** 2019-06-11 15:54 UTC

**Comment by kopollo** [comment] 2020-10-13 17:47
the solution is here  [localhost:8080](https://localhosts.mobi/8080)
