### ISSUE TITLE
Doesn't update changes made on html files

### ISSUE THREAD

**Issue by itaditya** [indexzero/http-server#287] opened 2016-06-20 11:18 UTC
When I'm changing the content in an Angular app , I don't restart the server just refresh the browser, it still shows old content .
What o do here ?

**Comment by derhuerst** [comment] 2016-06-20 12:07
`http-server` serves an [`ETag`](https://en.wikipedia.org/wiki/HTTP_ETag) with every response to tell the browser if the content changed. If I serve a directory containing `foo.html` and then modify `foo.html`, it correctly updates the `ETag`. Therefore, Firefox shows me the updated version of the file.

**Comment by vijaypatoliya** [comment] 2016-06-29 17:31
Same issue. Doesn't update changes made on html files

**Comment by derhuerst** [comment] 2016-06-29 22:39
Please check with the dev tools if `http-server` serves a different `ETag` or the same together with an `304 Not modified` header.

**Comment by gagan-bansal** [comment] 2016-09-13 04:53
Its working fine, sends the same together with an `304 Not modified` header.

**Comment by derhuerst** [comment] 2016-09-13 08:30
So why should something else be shown then? If the response hasn't been modified since the last request.

**Comment by gagan-bansal** [comment] 2016-09-14 06:39
@derhuerst I just mean that as its absolutely working as expected so issue can be closed.

**Comment by ObaidUrRehman** [comment] 2016-09-29 08:01
I have the exact same case with html files. In my case I modified one of my html file, refreshed chrome browser but http-server served with old `last-modified` date and same `etag`. The `cache-control:max-age=3600` header was set. After 3600s chrome does invalidate the cached html file and gets a new one. 

So I guess for some reason http-server is serving cached files. I wonder why!

**Comment by derhuerst** [comment] 2016-10-06 17:28
@ObaidUrRehman `http-server@0.9.0` has bedn released, including the #207. What is your `http-server` version? You can check with `npm ls --depth 0` or `npm ls -g --depth 0`.

**Comment by ObaidUrRehman** [comment] 2016-10-06 17:43
@derhuerst I am using `http-server0.9.0` yet I still get this issue. My node is `v4.4.4`.

**Comment by derhuerst** [comment] 2016-10-08 11:24
Would you mind updating to `4.4.7` or `4.6.0`? I haven't checked, but there might have been bugfixes related to this.

**Comment by hurkanakbiyik** [comment] 2016-11-04 14:56
I am using http-server0.9.0 and nodejs v6.9.1 and npm 1.4.21. I have same issue.

**Comment by jokeyrhyme** [comment] 2016-11-21 04:35
I run `http-server -c-1` to disable caches. Works well. Very refresh friendly. :)

**Comment by thomasdebruin** [comment] 2017-02-14 16:45
Also using http-server@0.9.0 and Node v6.9.5 LTS on window 8s, not able to disable the caching, tried chrome and forefox with devtools open, caching disabled, but same issue: always one or some more seconds of caching

**Comment by aretw0** [comment] 2017-09-05 18:54
Using node v6.11.2 and http-server@0.10.0 on windows 7.
Same issue. Doesn't update changes made on html or js files.
What can i do? I've already try `http-server -c-1`
Restart my machine every time i want to host my own app is hard.

**Comment by eshwergowda** [comment] 2017-10-27 09:46
The http-server docs mention that there's a parameter to configure the cache-control header, and it fixed the problem. The fix is to change this line in package.json:

`  "start": "http-server -a localhost -p 8000",
`
to 

`  "start": "http-server -a localhost -p 8000 -c-1",
`

**Comment by thornjad** [comment] 2019-02-17 22:08
@aretw0 Are you still seeing the same behavior on the latest versions of http-server and node?

**Comment by nickjgentile** [comment] 2019-02-20 15:46
> @aretw0 Are you still seeing the same behavior on the latest versions of http-server and node?

I am currently experiencing this issue on v 0.11.1 with the following start script: `"start": "http-server -p ${PORT:=5000} -c-1",`

**Comment by aretw0** [comment] 2019-02-21 19:12
> 
> 
> @aretw0 Are you still seeing the same behavior on the latest versions of http-server and node?

@thornjad 
I'm not using http-server so frequently, not anymore. I think this behaviour is more about the SO than something else.

**Comment by thornjad** [comment] 2019-04-29 14:16
Closing as a duplicate of #149 which is solved by #326

**Closed by thornjad** 2019-04-29 14:16 UTC
